{
 "title": "XES",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Recent Events",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  *\nFROM event\nWHERE\n  $__timeFilter(date)\nORDER BY date desc\nLIMIT 100"
    }
   ]
  },
  {
   "title": "Recent BPIC15_3.xes events",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  date AS \"time\",\n  *\nFROM event\nWHERE\n  $__timeFilter(date) \n  AND source = 'BPIC15_3.xes'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "KPI",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  source AS metric,\n  count(processinstance) AS \"processinstance\"\nFROM event\nWHERE\n  $__timeFilter(date)\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "Process Instances BPIC15_3.xes",
   "type": "graph",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  processinstance AS metric,\n  count(source) AS \"count\"\nFROM event\nWHERE\n  $__timeFilter(date)\n  AND source = 'BPIC15_3.xes'\nGROUP BY 1, processinstance, source,2\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "All Events",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(date,$__interval),\n  source AS metric,\n  count(source) AS \"value\"\nFROM event\nWHERE\n  $__timeFilter(date)\nGROUP BY 1,2\nORDER BY 1,2"
    }
   ]
  }
 ]
}